import type { Metadata } from "next";
import { Pacifico, Montserrat } from "next/font/google";
import "./globals.css";

const pacifico = Pacifico({ weight: "400", subsets: ["latin"] });
const montserrat = Montserrat({ weight: ["400", "800"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${pacifico.className}`}>
        {children}
      </body>
    </html>
  );
}